### ISSUE TITLE
Failed in version 0.53.1

### ISSUE THREAD

**Issue by EVANGELION-Air** [lwd-temp/IzaiahSun-Community.PowerToys.Run.Plugin.Everything#2]
This is only a tip since here is not the Source Code for embing Everthing into Powertoys

**Comment by lwd-temp** [comment]
This Repo is just a fork of https://github.com/IzaiahSun/PowerToys .
@IzaiahSun did all the work and I just put the binary here.
Please contact @IzaiahSun or fix the plugin with @IzaiahSun 's source code.
