### ISSUE TITLE
Update the Plugin to Make It Compatible with the Latest Version of PTR

### ISSUE THREAD

**Issue by xuangeyouneihan** [lwd-temp/IzaiahSun-Community.PowerToys.Run.Plugin.Everything#3]
As the title, this plugin failed in the latest version of Powertoys.

**Comment by lwd-temp** [comment]
This Repo is just a fork of https://github.com/IzaiahSun/PowerToys .
@IzaiahSun did all the work and I just put the binary here.
Please contact @IzaiahSun or fix the plugin with @IzaiahSun 's source code.
